CREATE TABLE IF NOT EXISTS cards (
    id         TEXT PRIMARY KEY,
    data       BLOB NOT NULL,
    version    INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
