ALTER TABLE cards ADD COLUMN dirty          INTEGER NOT NULL DEFAULT 0;
ALTER TABLE cards ADD COLUMN deleted        INTEGER NOT NULL DEFAULT 0;
ALTER TABLE cards ADD COLUMN base_version   INTEGER NOT NULL DEFAULT 0;
ALTER TABLE cards ADD COLUMN conflict       INTEGER NOT NULL DEFAULT 0;
ALTER TABLE cards ADD COLUMN server_blob    BLOB;
ALTER TABLE cards ADD COLUMN server_version INTEGER;

ALTER TABLE passwords ADD COLUMN dirty          INTEGER NOT NULL DEFAULT 0;
ALTER TABLE passwords ADD COLUMN deleted        INTEGER NOT NULL DEFAULT 0;
ALTER TABLE passwords ADD COLUMN base_version   INTEGER NOT NULL DEFAULT 0;
ALTER TABLE passwords ADD COLUMN conflict       INTEGER NOT NULL DEFAULT 0;
ALTER TABLE passwords ADD COLUMN server_blob    BLOB;
ALTER TABLE passwords ADD COLUMN server_version INTEGER;

ALTER TABLE notes ADD COLUMN dirty          INTEGER NOT NULL DEFAULT 0;
ALTER TABLE notes ADD COLUMN deleted        INTEGER NOT NULL DEFAULT 0;
ALTER TABLE notes ADD COLUMN base_version   INTEGER NOT NULL DEFAULT 0;
ALTER TABLE notes ADD COLUMN conflict       INTEGER NOT NULL DEFAULT 0;
ALTER TABLE notes ADD COLUMN server_blob    BLOB;
ALTER TABLE notes ADD COLUMN server_version INTEGER;
