services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: gophkeeper
      POSTGRES_PASSWORD: gophkeeper
      POSTGRES_DB: gophkeeper
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gophkeeper -d gophkeeper"]
      interval: 5s
      timeout: 3s
      retries: 5

  server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      TRANSPORT: "grpc"
      ADDRESS: ":8080"
      APP_MODE: "development"
      DATABASE_DSN: "postgres://gophkeeper:gophkeeper@db:5432/gophkeeper?sslmode=disable"
    ports:
      - "8080:8080"

volumes:
  pgdata:
