// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: card/v1/card.proto

package cardv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Card is a user's client-side encrypted card record.
type Card struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Data        []byte                 `protobuf:"bytes,2,opt,name=data"`
	xxx_hidden_Version     int64                  `protobuf:"varint,3,opt,name=version"`
	xxx_hidden_CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt"`
	xxx_hidden_UpdatedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_card_v1_card_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_card_v1_card_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Card) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *Card) GetData() []byte {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *Card) GetVersion() int64 {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return 0
}

func (x *Card) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *Card) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_UpdatedAt
	}
	return nil
}

func (x *Card) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *Card) SetData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *Card) SetVersion(v int64) {
	x.xxx_hidden_Version = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *Card) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *Card) SetUpdatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_UpdatedAt = v
}

func (x *Card) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Card) HasData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Card) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Card) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *Card) HasUpdatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UpdatedAt != nil
}

func (x *Card) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *Card) ClearData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Data = nil
}

func (x *Card) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Version = 0
}

func (x *Card) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

func (x *Card) ClearUpdatedAt() {
	x.xxx_hidden_UpdatedAt = nil
}

type Card_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id        *string
	Data      []byte
	Version   *int64
	CreatedAt *timestamppb.Timestamp
	UpdatedAt *timestamppb.Timestamp
}

func (b0 Card_builder) Build() *Card {
	m0 := &Card{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_Id = b.Id
	}
	if b.Data != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_Data = b.Data
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_Version = *b.Version
	}
	x.xxx_hidden_CreatedAt = b.CreatedAt
	x.xxx_hidden_UpdatedAt = b.UpdatedAt
	return m0
}

type AddRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Data        []byte                 `protobuf:"bytes,1,opt,name=data"`
	xxx_hidden_Id          *string                `protobuf:"bytes,2,opt,name=id"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AddRequest) Reset() {
	*x = AddRequest{}
	mi := &file_card_v1_card_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRequest) ProtoMessage() {}

func (x *AddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_card_v1_card_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AddRequest) GetData() []byte {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *AddRequest) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *AddRequest) SetData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *AddRequest) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *AddRequest) HasData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AddRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *AddRequest) ClearData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Data = nil
}

func (x *AddRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Id = nil
}

type AddRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Data []byte
	Id   *string
}

func (b0 AddRequest_builder) Build() *AddRequest {
	m0 := &AddRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Data != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Data = b.Data
	}
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Id = b.Id
	}
	return m0
}

type AddResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Card *Card                  `protobuf:"bytes,1,opt,name=card"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AddResponse) Reset() {
	*x = AddResponse{}
	mi := &file_card_v1_card_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddResponse) ProtoMessage() {}

func (x *AddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_card_v1_card_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AddResponse) GetCard() *Card {
	if x != nil {
		return x.xxx_hidden_Card
	}
	return nil
}

func (x *AddResponse) SetCard(v *Card) {
	x.xxx_hidden_Card = v
}

func (x *AddResponse) HasCard() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Card != nil
}

func (x *AddResponse) ClearCard() {
	x.xxx_hidden_Card = nil
}

type AddResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Card *Card
}

func (b0 AddResponse_builder) Build() *AddResponse {
	m0 := &AddResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Card = b.Card
	return m0
}

type GetRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_card_v1_card_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_card_v1_card_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetRequest) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *GetRequest) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *GetRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

type GetRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id *string
}

func (b0 GetRequest_builder) Build() *GetRequest {
	m0 := &GetRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Id = b.Id
	}
	return m0
}

type GetResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Card *Card                  `protobuf:"bytes,1,opt,name=card"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_card_v1_card_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_card_v1_card_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetResponse) GetCard() *Card {
	if x != nil {
		return x.xxx_hidden_Card
	}
	return nil
}

func (x *GetResponse) SetCard(v *Card) {
	x.xxx_hidden_Card = v
}

func (x *GetResponse) HasCard() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Card != nil
}

func (x *GetResponse) ClearCard() {
	x.xxx_hidden_Card = nil
}

type GetResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Card *Card
}

func (b0 GetResponse_builder) Build() *GetResponse {
	m0 := &GetResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Card = b.Card
	return m0
}

// ListRequest pages a user's cards in chunks.
type ListRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_LastId      *string                `protobuf:"bytes,1,opt,name=last_id,json=lastId"`
	xxx_hidden_Limit       int32                  `protobuf:"varint,2,opt,name=limit"`
	xxx_hidden_Offset      int32                  `protobuf:"varint,3,opt,name=offset"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_card_v1_card_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_card_v1_card_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListRequest) GetLastId() string {
	if x != nil {
		if x.xxx_hidden_LastId != nil {
			return *x.xxx_hidden_LastId
		}
		return ""
	}
	return ""
}

func (x *ListRequest) GetLimit() int32 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *ListRequest) GetOffset() int32 {
	if x != nil {
		return x.xxx_hidden_Offset
	}
	return 0
}

func (x *ListRequest) SetLastId(v string) {
	x.xxx_hidden_LastId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *ListRequest) SetLimit(v int32) {
	x.xxx_hidden_Limit = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *ListRequest) SetOffset(v int32) {
	x.xxx_hidden_Offset = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *ListRequest) HasLastId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ListRequest) HasLimit() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ListRequest) HasOffset() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ListRequest) ClearLastId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_LastId = nil
}

func (x *ListRequest) ClearLimit() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Limit = 0
}

func (x *ListRequest) ClearOffset() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Offset = 0
}

type ListRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	LastId *string
	Limit  *int32
	Offset *int32
}

func (b0 ListRequest_builder) Build() *ListRequest {
	m0 := &ListRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.LastId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_LastId = b.LastId
	}
	if b.Limit != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Limit = *b.Limit
	}
	if b.Offset != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Offset = *b.Offset
	}
	return m0
}

type ListResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Cards *[]*Card               `protobuf:"bytes,1,rep,name=cards"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_card_v1_card_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_card_v1_card_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListResponse) GetCards() []*Card {
	if x != nil {
		if x.xxx_hidden_Cards != nil {
			return *x.xxx_hidden_Cards
		}
	}
	return nil
}

func (x *ListResponse) SetCards(v []*Card) {
	x.xxx_hidden_Cards = &v
}

type ListResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Cards []*Card
}

func (b0 ListResponse_builder) Build() *ListResponse {
	m0 := &ListResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Cards = &b.Cards
	return m0
}

type UpdateRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Data        []byte                 `protobuf:"bytes,2,opt,name=data"`
	xxx_hidden_Version     int64                  `protobuf:"varint,3,opt,name=version"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_card_v1_card_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_card_v1_card_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateRequest) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *UpdateRequest) GetData() []byte {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *UpdateRequest) GetVersion() int64 {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return 0
}

func (x *UpdateRequest) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *UpdateRequest) SetData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *UpdateRequest) SetVersion(v int64) {
	x.xxx_hidden_Version = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *UpdateRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *UpdateRequest) HasData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *UpdateRequest) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *UpdateRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *UpdateRequest) ClearData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Data = nil
}

func (x *UpdateRequest) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Version = 0
}

type UpdateRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id      *string
	Data    []byte
	Version *int64
}

func (b0 UpdateRequest_builder) Build() *UpdateRequest {
	m0 := &UpdateRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Id = b.Id
	}
	if b.Data != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Data = b.Data
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Version = *b.Version
	}
	return m0
}

type UpdateResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Card *Card                  `protobuf:"bytes,1,opt,name=card"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_card_v1_card_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_card_v1_card_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateResponse) GetCard() *Card {
	if x != nil {
		return x.xxx_hidden_Card
	}
	return nil
}

func (x *UpdateResponse) SetCard(v *Card) {
	x.xxx_hidden_Card = v
}

func (x *UpdateResponse) HasCard() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Card != nil
}

func (x *UpdateResponse) ClearCard() {
	x.xxx_hidden_Card = nil
}

type UpdateResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Card *Card
}

func (b0 UpdateResponse_builder) Build() *UpdateResponse {
	m0 := &UpdateResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Card = b.Card
	return m0
}

type DeleteRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_card_v1_card_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_card_v1_card_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteRequest) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *DeleteRequest) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *DeleteRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DeleteRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

type DeleteRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id *string
}

func (b0 DeleteRequest_builder) Build() *DeleteRequest {
	m0 := &DeleteRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Id = b.Id
	}
	return m0
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_card_v1_card_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_card_v1_card_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type DeleteResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 DeleteResponse_builder) Build() *DeleteResponse {
	m0 := &DeleteResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ChangesRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Since       *string                `protobuf:"bytes,1,opt,name=since"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ChangesRequest) Reset() {
	*x = ChangesRequest{}
	mi := &file_card_v1_card_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangesRequest) ProtoMessage() {}

func (x *ChangesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_card_v1_card_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ChangesRequest) GetSince() string {
	if x != nil {
		if x.xxx_hidden_Since != nil {
			return *x.xxx_hidden_Since
		}
		return ""
	}
	return ""
}

func (x *ChangesRequest) SetSince(v string) {
	x.xxx_hidden_Since = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *ChangesRequest) HasSince() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ChangesRequest) ClearSince() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Since = nil
}

type ChangesRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Since *string
}

func (b0 ChangesRequest_builder) Build() *ChangesRequest {
	m0 := &ChangesRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Since != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Since = b.Since
	}
	return m0
}

type CardChange struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Data        []byte                 `protobuf:"bytes,2,opt,name=data"`
	xxx_hidden_Version     int64                  `protobuf:"varint,3,opt,name=version"`
	xxx_hidden_Deleted     bool                   `protobuf:"varint,4,opt,name=deleted"`
	xxx_hidden_UpdatedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CardChange) Reset() {
	*x = CardChange{}
	mi := &file_card_v1_card_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardChange) ProtoMessage() {}

func (x *CardChange) ProtoReflect() protoreflect.Message {
	mi := &file_card_v1_card_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CardChange) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *CardChange) GetData() []byte {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *CardChange) GetVersion() int64 {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return 0
}

func (x *CardChange) GetDeleted() bool {
	if x != nil {
		return x.xxx_hidden_Deleted
	}
	return false
}

func (x *CardChange) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_UpdatedAt
	}
	return nil
}

func (x *CardChange) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *CardChange) SetData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *CardChange) SetVersion(v int64) {
	x.xxx_hidden_Version = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *CardChange) SetDeleted(v bool) {
	x.xxx_hidden_Deleted = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *CardChange) SetUpdatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_UpdatedAt = v
}

func (x *CardChange) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CardChange) HasData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CardChange) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *CardChange) HasDeleted() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *CardChange) HasUpdatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UpdatedAt != nil
}

func (x *CardChange) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *CardChange) ClearData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Data = nil
}

func (x *CardChange) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Version = 0
}

func (x *CardChange) ClearDeleted() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Deleted = false
}

func (x *CardChange) ClearUpdatedAt() {
	x.xxx_hidden_UpdatedAt = nil
}

type CardChange_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id        *string
	Data      []byte
	Version   *int64
	Deleted   *bool
	UpdatedAt *timestamppb.Timestamp
}

func (b0 CardChange_builder) Build() *CardChange {
	m0 := &CardChange{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_Id = b.Id
	}
	if b.Data != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_Data = b.Data
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_Version = *b.Version
	}
	if b.Deleted != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_Deleted = *b.Deleted
	}
	x.xxx_hidden_UpdatedAt = b.UpdatedAt
	return m0
}

type ChangesResponse struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Changes *[]*CardChange         `protobuf:"bytes,1,rep,name=changes"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ChangesResponse) Reset() {
	*x = ChangesResponse{}
	mi := &file_card_v1_card_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangesResponse) ProtoMessage() {}

func (x *ChangesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_card_v1_card_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ChangesResponse) GetChanges() []*CardChange {
	if x != nil {
		if x.xxx_hidden_Changes != nil {
			return *x.xxx_hidden_Changes
		}
	}
	return nil
}

func (x *ChangesResponse) SetChanges(v []*CardChange) {
	x.xxx_hidden_Changes = &v
}

type ChangesResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Changes []*CardChange
}

func (b0 ChangesResponse_builder) Build() *ChangesResponse {
	m0 := &ChangesResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Changes = &b.Changes
	return m0
}

var File_card_v1_card_proto protoreflect.FileDescriptor

const file_card_v1_card_proto_rawDesc = "" +
	"\n" +
	"\x12card/v1/card.proto\x12\acard.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xba\x01\n" +
	"\x04Card\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"0\n" +
	"\n" +
	"AddRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"0\n" +
	"\vAddResponse\x12!\n" +
	"\x04card\x18\x01 \x01(\v2\r.card.v1.CardR\x04card\"\x1c\n" +
	"\n" +
	"GetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"0\n" +
	"\vGetResponse\x12!\n" +
	"\x04card\x18\x01 \x01(\v2\r.card.v1.CardR\x04card\"T\n" +
	"\vListRequest\x12\x17\n" +
	"\alast_id\x18\x01 \x01(\tR\x06lastId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"3\n" +
	"\fListResponse\x12#\n" +
	"\x05cards\x18\x01 \x03(\v2\r.card.v1.CardR\x05cards\"M\n" +
	"\rUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\"3\n" +
	"\x0eUpdateResponse\x12!\n" +
	"\x04card\x18\x01 \x01(\v2\r.card.v1.CardR\x04card\"\x1f\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x10\n" +
	"\x0eDeleteResponse\"&\n" +
	"\x0eChangesRequest\x12\x14\n" +
	"\x05since\x18\x01 \x01(\tR\x05since\"\x9f\x01\n" +
	"\n" +
	"CardChange\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\x12\x18\n" +
	"\adeleted\x18\x04 \x01(\bR\adeleted\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"@\n" +
	"\x0fChangesResponse\x12-\n" +
	"\achanges\x18\x01 \x03(\v2\x13.card.v1.CardChangeR\achanges2\xda\x02\n" +
	"\vCardService\x120\n" +
	"\x03Add\x12\x13.card.v1.AddRequest\x1a\x14.card.v1.AddResponse\x120\n" +
	"\x03Get\x12\x13.card.v1.GetRequest\x1a\x14.card.v1.GetResponse\x123\n" +
	"\x04List\x12\x14.card.v1.ListRequest\x1a\x15.card.v1.ListResponse\x129\n" +
	"\x06Update\x12\x16.card.v1.UpdateRequest\x1a\x17.card.v1.UpdateResponse\x129\n" +
	"\x06Delete\x12\x16.card.v1.DeleteRequest\x1a\x17.card.v1.DeleteResponse\x12<\n" +
	"\aChanges\x12\x17.card.v1.ChangesRequest\x1a\x18.card.v1.ChangesResponseB1Z/gophkeeper/internal/shared/proto/card/v1;cardv1b\beditionsp\xe8\a"

var file_card_v1_card_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_card_v1_card_proto_goTypes = []any{
	(*Card)(nil),                  // 0: card.v1.Card
	(*AddRequest)(nil),            // 1: card.v1.AddRequest
	(*AddResponse)(nil),           // 2: card.v1.AddResponse
	(*GetRequest)(nil),            // 3: card.v1.GetRequest
	(*GetResponse)(nil),           // 4: card.v1.GetResponse
	(*ListRequest)(nil),           // 5: card.v1.ListRequest
	(*ListResponse)(nil),          // 6: card.v1.ListResponse
	(*UpdateRequest)(nil),         // 7: card.v1.UpdateRequest
	(*UpdateResponse)(nil),        // 8: card.v1.UpdateResponse
	(*DeleteRequest)(nil),         // 9: card.v1.DeleteRequest
	(*DeleteResponse)(nil),        // 10: card.v1.DeleteResponse
	(*ChangesRequest)(nil),        // 11: card.v1.ChangesRequest
	(*CardChange)(nil),            // 12: card.v1.CardChange
	(*ChangesResponse)(nil),       // 13: card.v1.ChangesResponse
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
}
var file_card_v1_card_proto_depIdxs = []int32{
	14, // 0: card.v1.Card.created_at:type_name -> google.protobuf.Timestamp
	14, // 1: card.v1.Card.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: card.v1.AddResponse.card:type_name -> card.v1.Card
	0,  // 3: card.v1.GetResponse.card:type_name -> card.v1.Card
	0,  // 4: card.v1.ListResponse.cards:type_name -> card.v1.Card
	0,  // 5: card.v1.UpdateResponse.card:type_name -> card.v1.Card
	14, // 6: card.v1.CardChange.updated_at:type_name -> google.protobuf.Timestamp
	12, // 7: card.v1.ChangesResponse.changes:type_name -> card.v1.CardChange
	1,  // 8: card.v1.CardService.Add:input_type -> card.v1.AddRequest
	3,  // 9: card.v1.CardService.Get:input_type -> card.v1.GetRequest
	5,  // 10: card.v1.CardService.List:input_type -> card.v1.ListRequest
	7,  // 11: card.v1.CardService.Update:input_type -> card.v1.UpdateRequest
	9,  // 12: card.v1.CardService.Delete:input_type -> card.v1.DeleteRequest
	11, // 13: card.v1.CardService.Changes:input_type -> card.v1.ChangesRequest
	2,  // 14: card.v1.CardService.Add:output_type -> card.v1.AddResponse
	4,  // 15: card.v1.CardService.Get:output_type -> card.v1.GetResponse
	6,  // 16: card.v1.CardService.List:output_type -> card.v1.ListResponse
	8,  // 17: card.v1.CardService.Update:output_type -> card.v1.UpdateResponse
	10, // 18: card.v1.CardService.Delete:output_type -> card.v1.DeleteResponse
	13, // 19: card.v1.CardService.Changes:output_type -> card.v1.ChangesResponse
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_card_v1_card_proto_init() }
func file_card_v1_card_proto_init() {
	if File_card_v1_card_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_card_v1_card_proto_rawDesc), len(file_card_v1_card_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_card_v1_card_proto_goTypes,
		DependencyIndexes: file_card_v1_card_proto_depIdxs,
		MessageInfos:      file_card_v1_card_proto_msgTypes,
	}.Build()
	File_card_v1_card_proto = out.File
	file_card_v1_card_proto_goTypes = nil
	file_card_v1_card_proto_depIdxs = nil
}
