// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: user/v1/card.proto

package cardv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Card struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id             *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Pan            *string                `protobuf:"bytes,2,opt,name=pan"`
	xxx_hidden_CardholderName *string                `protobuf:"bytes,3,opt,name=cardholder_name,json=cardholderName"`
	xxx_hidden_Expiry         *string                `protobuf:"bytes,4,opt,name=expiry"`
	xxx_hidden_Cvv            *string                `protobuf:"bytes,5,opt,name=cvv"`
	xxx_hidden_Meta           *string                `protobuf:"bytes,6,opt,name=meta"`
	xxx_hidden_CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt"`
	xxx_hidden_UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt"`
	XXX_raceDetectHookData    protoimpl.RaceDetectHookData
	XXX_presence              [1]uint32
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_user_v1_card_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_card_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Card) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *Card) GetPan() string {
	if x != nil {
		if x.xxx_hidden_Pan != nil {
			return *x.xxx_hidden_Pan
		}
		return ""
	}
	return ""
}

func (x *Card) GetCardholderName() string {
	if x != nil {
		if x.xxx_hidden_CardholderName != nil {
			return *x.xxx_hidden_CardholderName
		}
		return ""
	}
	return ""
}

func (x *Card) GetExpiry() string {
	if x != nil {
		if x.xxx_hidden_Expiry != nil {
			return *x.xxx_hidden_Expiry
		}
		return ""
	}
	return ""
}

func (x *Card) GetCvv() string {
	if x != nil {
		if x.xxx_hidden_Cvv != nil {
			return *x.xxx_hidden_Cvv
		}
		return ""
	}
	return ""
}

func (x *Card) GetMeta() string {
	if x != nil {
		if x.xxx_hidden_Meta != nil {
			return *x.xxx_hidden_Meta
		}
		return ""
	}
	return ""
}

func (x *Card) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *Card) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_UpdatedAt
	}
	return nil
}

func (x *Card) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 8)
}

func (x *Card) SetPan(v string) {
	x.xxx_hidden_Pan = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 8)
}

func (x *Card) SetCardholderName(v string) {
	x.xxx_hidden_CardholderName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 8)
}

func (x *Card) SetExpiry(v string) {
	x.xxx_hidden_Expiry = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 8)
}

func (x *Card) SetCvv(v string) {
	x.xxx_hidden_Cvv = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 8)
}

func (x *Card) SetMeta(v string) {
	x.xxx_hidden_Meta = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 8)
}

func (x *Card) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *Card) SetUpdatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_UpdatedAt = v
}

func (x *Card) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Card) HasPan() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Card) HasCardholderName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Card) HasExpiry() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Card) HasCvv() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Card) HasMeta() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *Card) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *Card) HasUpdatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UpdatedAt != nil
}

func (x *Card) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *Card) ClearPan() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Pan = nil
}

func (x *Card) ClearCardholderName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_CardholderName = nil
}

func (x *Card) ClearExpiry() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Expiry = nil
}

func (x *Card) ClearCvv() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Cvv = nil
}

func (x *Card) ClearMeta() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Meta = nil
}

func (x *Card) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

func (x *Card) ClearUpdatedAt() {
	x.xxx_hidden_UpdatedAt = nil
}

type Card_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id             *string
	Pan            *string
	CardholderName *string
	Expiry         *string
	Cvv            *string
	Meta           *string
	CreatedAt      *timestamppb.Timestamp
	UpdatedAt      *timestamppb.Timestamp
}

func (b0 Card_builder) Build() *Card {
	m0 := &Card{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 8)
		x.xxx_hidden_Id = b.Id
	}
	if b.Pan != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 8)
		x.xxx_hidden_Pan = b.Pan
	}
	if b.CardholderName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 8)
		x.xxx_hidden_CardholderName = b.CardholderName
	}
	if b.Expiry != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 8)
		x.xxx_hidden_Expiry = b.Expiry
	}
	if b.Cvv != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 8)
		x.xxx_hidden_Cvv = b.Cvv
	}
	if b.Meta != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 8)
		x.xxx_hidden_Meta = b.Meta
	}
	x.xxx_hidden_CreatedAt = b.CreatedAt
	x.xxx_hidden_UpdatedAt = b.UpdatedAt
	return m0
}

type AddRequest struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Pan            *string                `protobuf:"bytes,1,opt,name=pan"`
	xxx_hidden_CardholderName *string                `protobuf:"bytes,2,opt,name=cardholder_name,json=cardholderName"`
	xxx_hidden_Expiry         *string                `protobuf:"bytes,3,opt,name=expiry"`
	xxx_hidden_Cvv            *string                `protobuf:"bytes,4,opt,name=cvv"`
	xxx_hidden_Meta           *string                `protobuf:"bytes,5,opt,name=meta"`
	XXX_raceDetectHookData    protoimpl.RaceDetectHookData
	XXX_presence              [1]uint32
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *AddRequest) Reset() {
	*x = AddRequest{}
	mi := &file_user_v1_card_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRequest) ProtoMessage() {}

func (x *AddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_card_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AddRequest) GetPan() string {
	if x != nil {
		if x.xxx_hidden_Pan != nil {
			return *x.xxx_hidden_Pan
		}
		return ""
	}
	return ""
}

func (x *AddRequest) GetCardholderName() string {
	if x != nil {
		if x.xxx_hidden_CardholderName != nil {
			return *x.xxx_hidden_CardholderName
		}
		return ""
	}
	return ""
}

func (x *AddRequest) GetExpiry() string {
	if x != nil {
		if x.xxx_hidden_Expiry != nil {
			return *x.xxx_hidden_Expiry
		}
		return ""
	}
	return ""
}

func (x *AddRequest) GetCvv() string {
	if x != nil {
		if x.xxx_hidden_Cvv != nil {
			return *x.xxx_hidden_Cvv
		}
		return ""
	}
	return ""
}

func (x *AddRequest) GetMeta() string {
	if x != nil {
		if x.xxx_hidden_Meta != nil {
			return *x.xxx_hidden_Meta
		}
		return ""
	}
	return ""
}

func (x *AddRequest) SetPan(v string) {
	x.xxx_hidden_Pan = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *AddRequest) SetCardholderName(v string) {
	x.xxx_hidden_CardholderName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *AddRequest) SetExpiry(v string) {
	x.xxx_hidden_Expiry = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *AddRequest) SetCvv(v string) {
	x.xxx_hidden_Cvv = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *AddRequest) SetMeta(v string) {
	x.xxx_hidden_Meta = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *AddRequest) HasPan() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AddRequest) HasCardholderName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *AddRequest) HasExpiry() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *AddRequest) HasCvv() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *AddRequest) HasMeta() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *AddRequest) ClearPan() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Pan = nil
}

func (x *AddRequest) ClearCardholderName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_CardholderName = nil
}

func (x *AddRequest) ClearExpiry() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Expiry = nil
}

func (x *AddRequest) ClearCvv() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Cvv = nil
}

func (x *AddRequest) ClearMeta() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Meta = nil
}

type AddRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Pan            *string
	CardholderName *string
	Expiry         *string
	Cvv            *string
	Meta           *string
}

func (b0 AddRequest_builder) Build() *AddRequest {
	m0 := &AddRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Pan != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_Pan = b.Pan
	}
	if b.CardholderName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_CardholderName = b.CardholderName
	}
	if b.Expiry != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_Expiry = b.Expiry
	}
	if b.Cvv != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_Cvv = b.Cvv
	}
	if b.Meta != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_Meta = b.Meta
	}
	return m0
}

type AddResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Card *Card                  `protobuf:"bytes,1,opt,name=card"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AddResponse) Reset() {
	*x = AddResponse{}
	mi := &file_user_v1_card_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddResponse) ProtoMessage() {}

func (x *AddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_card_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AddResponse) GetCard() *Card {
	if x != nil {
		return x.xxx_hidden_Card
	}
	return nil
}

func (x *AddResponse) SetCard(v *Card) {
	x.xxx_hidden_Card = v
}

func (x *AddResponse) HasCard() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Card != nil
}

func (x *AddResponse) ClearCard() {
	x.xxx_hidden_Card = nil
}

type AddResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Card *Card
}

func (b0 AddResponse_builder) Build() *AddResponse {
	m0 := &AddResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Card = b.Card
	return m0
}

type GetRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_user_v1_card_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_card_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetRequest) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *GetRequest) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *GetRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

type GetRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id *string
}

func (b0 GetRequest_builder) Build() *GetRequest {
	m0 := &GetRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Id = b.Id
	}
	return m0
}

type GetResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Card *Card                  `protobuf:"bytes,1,opt,name=card"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_user_v1_card_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_card_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetResponse) GetCard() *Card {
	if x != nil {
		return x.xxx_hidden_Card
	}
	return nil
}

func (x *GetResponse) SetCard(v *Card) {
	x.xxx_hidden_Card = v
}

func (x *GetResponse) HasCard() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Card != nil
}

func (x *GetResponse) ClearCard() {
	x.xxx_hidden_Card = nil
}

type GetResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Card *Card
}

func (b0 GetResponse_builder) Build() *GetResponse {
	m0 := &GetResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Card = b.Card
	return m0
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_user_v1_card_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_card_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ListRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ListRequest_builder) Build() *ListRequest {
	m0 := &ListRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ListResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Cards *[]*Card               `protobuf:"bytes,1,rep,name=cards"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_user_v1_card_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_card_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListResponse) GetCards() []*Card {
	if x != nil {
		if x.xxx_hidden_Cards != nil {
			return *x.xxx_hidden_Cards
		}
	}
	return nil
}

func (x *ListResponse) SetCards(v []*Card) {
	x.xxx_hidden_Cards = &v
}

type ListResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Cards []*Card
}

func (b0 ListResponse_builder) Build() *ListResponse {
	m0 := &ListResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Cards = &b.Cards
	return m0
}

type UpdateRequest struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id             *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Pan            *string                `protobuf:"bytes,2,opt,name=pan"`
	xxx_hidden_CardholderName *string                `protobuf:"bytes,3,opt,name=cardholder_name,json=cardholderName"`
	xxx_hidden_Expiry         *string                `protobuf:"bytes,4,opt,name=expiry"`
	xxx_hidden_Cvv            *string                `protobuf:"bytes,5,opt,name=cvv"`
	xxx_hidden_Meta           *string                `protobuf:"bytes,6,opt,name=meta"`
	XXX_raceDetectHookData    protoimpl.RaceDetectHookData
	XXX_presence              [1]uint32
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_user_v1_card_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_card_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateRequest) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *UpdateRequest) GetPan() string {
	if x != nil {
		if x.xxx_hidden_Pan != nil {
			return *x.xxx_hidden_Pan
		}
		return ""
	}
	return ""
}

func (x *UpdateRequest) GetCardholderName() string {
	if x != nil {
		if x.xxx_hidden_CardholderName != nil {
			return *x.xxx_hidden_CardholderName
		}
		return ""
	}
	return ""
}

func (x *UpdateRequest) GetExpiry() string {
	if x != nil {
		if x.xxx_hidden_Expiry != nil {
			return *x.xxx_hidden_Expiry
		}
		return ""
	}
	return ""
}

func (x *UpdateRequest) GetCvv() string {
	if x != nil {
		if x.xxx_hidden_Cvv != nil {
			return *x.xxx_hidden_Cvv
		}
		return ""
	}
	return ""
}

func (x *UpdateRequest) GetMeta() string {
	if x != nil {
		if x.xxx_hidden_Meta != nil {
			return *x.xxx_hidden_Meta
		}
		return ""
	}
	return ""
}

func (x *UpdateRequest) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *UpdateRequest) SetPan(v string) {
	x.xxx_hidden_Pan = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *UpdateRequest) SetCardholderName(v string) {
	x.xxx_hidden_CardholderName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *UpdateRequest) SetExpiry(v string) {
	x.xxx_hidden_Expiry = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *UpdateRequest) SetCvv(v string) {
	x.xxx_hidden_Cvv = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *UpdateRequest) SetMeta(v string) {
	x.xxx_hidden_Meta = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 6)
}

func (x *UpdateRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *UpdateRequest) HasPan() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *UpdateRequest) HasCardholderName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *UpdateRequest) HasExpiry() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *UpdateRequest) HasCvv() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *UpdateRequest) HasMeta() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *UpdateRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *UpdateRequest) ClearPan() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Pan = nil
}

func (x *UpdateRequest) ClearCardholderName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_CardholderName = nil
}

func (x *UpdateRequest) ClearExpiry() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Expiry = nil
}

func (x *UpdateRequest) ClearCvv() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Cvv = nil
}

func (x *UpdateRequest) ClearMeta() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Meta = nil
}

type UpdateRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id             *string
	Pan            *string
	CardholderName *string
	Expiry         *string
	Cvv            *string
	Meta           *string
}

func (b0 UpdateRequest_builder) Build() *UpdateRequest {
	m0 := &UpdateRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_Id = b.Id
	}
	if b.Pan != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_Pan = b.Pan
	}
	if b.CardholderName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_CardholderName = b.CardholderName
	}
	if b.Expiry != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_Expiry = b.Expiry
	}
	if b.Cvv != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_Cvv = b.Cvv
	}
	if b.Meta != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 6)
		x.xxx_hidden_Meta = b.Meta
	}
	return m0
}

type UpdateResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Card *Card                  `protobuf:"bytes,1,opt,name=card"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_user_v1_card_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_card_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateResponse) GetCard() *Card {
	if x != nil {
		return x.xxx_hidden_Card
	}
	return nil
}

func (x *UpdateResponse) SetCard(v *Card) {
	x.xxx_hidden_Card = v
}

func (x *UpdateResponse) HasCard() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Card != nil
}

func (x *UpdateResponse) ClearCard() {
	x.xxx_hidden_Card = nil
}

type UpdateResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Card *Card
}

func (b0 UpdateResponse_builder) Build() *UpdateResponse {
	m0 := &UpdateResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Card = b.Card
	return m0
}

type DeleteRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_user_v1_card_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_card_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteRequest) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *DeleteRequest) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *DeleteRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DeleteRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

type DeleteRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id *string
}

func (b0 DeleteRequest_builder) Build() *DeleteRequest {
	m0 := &DeleteRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Id = b.Id
	}
	return m0
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_user_v1_card_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_card_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type DeleteResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 DeleteResponse_builder) Build() *DeleteResponse {
	m0 := &DeleteResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_user_v1_card_proto protoreflect.FileDescriptor

const file_user_v1_card_proto_rawDesc = "" +
	"\n" +
	"\x12user/v1/card.proto\x12\acard.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x85\x02\n" +
	"\x04Card\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03pan\x18\x02 \x01(\tR\x03pan\x12'\n" +
	"\x0fcardholder_name\x18\x03 \x01(\tR\x0ecardholderName\x12\x16\n" +
	"\x06expiry\x18\x04 \x01(\tR\x06expiry\x12\x10\n" +
	"\x03cvv\x18\x05 \x01(\tR\x03cvv\x12\x12\n" +
	"\x04meta\x18\x06 \x01(\tR\x04meta\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x85\x01\n" +
	"\n" +
	"AddRequest\x12\x10\n" +
	"\x03pan\x18\x01 \x01(\tR\x03pan\x12'\n" +
	"\x0fcardholder_name\x18\x02 \x01(\tR\x0ecardholderName\x12\x16\n" +
	"\x06expiry\x18\x03 \x01(\tR\x06expiry\x12\x10\n" +
	"\x03cvv\x18\x04 \x01(\tR\x03cvv\x12\x12\n" +
	"\x04meta\x18\x05 \x01(\tR\x04meta\"0\n" +
	"\vAddResponse\x12!\n" +
	"\x04card\x18\x01 \x01(\v2\r.card.v1.CardR\x04card\"\x1c\n" +
	"\n" +
	"GetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"0\n" +
	"\vGetResponse\x12!\n" +
	"\x04card\x18\x01 \x01(\v2\r.card.v1.CardR\x04card\"\r\n" +
	"\vListRequest\"3\n" +
	"\fListResponse\x12#\n" +
	"\x05cards\x18\x01 \x03(\v2\r.card.v1.CardR\x05cards\"\x98\x01\n" +
	"\rUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03pan\x18\x02 \x01(\tR\x03pan\x12'\n" +
	"\x0fcardholder_name\x18\x03 \x01(\tR\x0ecardholderName\x12\x16\n" +
	"\x06expiry\x18\x04 \x01(\tR\x06expiry\x12\x10\n" +
	"\x03cvv\x18\x05 \x01(\tR\x03cvv\x12\x12\n" +
	"\x04meta\x18\x06 \x01(\tR\x04meta\"3\n" +
	"\x0eUpdateResponse\x12!\n" +
	"\x04card\x18\x01 \x01(\v2\r.card.v1.CardR\x04card\"\x1f\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x10\n" +
	"\x0eDeleteResponse2\x9c\x02\n" +
	"\vCardService\x120\n" +
	"\x03Add\x12\x13.card.v1.AddRequest\x1a\x14.card.v1.AddResponse\x120\n" +
	"\x03Get\x12\x13.card.v1.GetRequest\x1a\x14.card.v1.GetResponse\x123\n" +
	"\x04List\x12\x14.card.v1.ListRequest\x1a\x15.card.v1.ListResponse\x129\n" +
	"\x06Update\x12\x16.card.v1.UpdateRequest\x1a\x17.card.v1.UpdateResponse\x129\n" +
	"\x06Delete\x12\x16.card.v1.DeleteRequest\x1a\x17.card.v1.DeleteResponseB1Z/gophkeeper/internal/shared/proto/card/v1;cardv1b\beditionsp\xe8\a"

var file_user_v1_card_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_user_v1_card_proto_goTypes = []any{
	(*Card)(nil),                  // 0: card.v1.Card
	(*AddRequest)(nil),            // 1: card.v1.AddRequest
	(*AddResponse)(nil),           // 2: card.v1.AddResponse
	(*GetRequest)(nil),            // 3: card.v1.GetRequest
	(*GetResponse)(nil),           // 4: card.v1.GetResponse
	(*ListRequest)(nil),           // 5: card.v1.ListRequest
	(*ListResponse)(nil),          // 6: card.v1.ListResponse
	(*UpdateRequest)(nil),         // 7: card.v1.UpdateRequest
	(*UpdateResponse)(nil),        // 8: card.v1.UpdateResponse
	(*DeleteRequest)(nil),         // 9: card.v1.DeleteRequest
	(*DeleteResponse)(nil),        // 10: card.v1.DeleteResponse
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_user_v1_card_proto_depIdxs = []int32{
	11, // 0: card.v1.Card.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: card.v1.Card.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: card.v1.AddResponse.card:type_name -> card.v1.Card
	0,  // 3: card.v1.GetResponse.card:type_name -> card.v1.Card
	0,  // 4: card.v1.ListResponse.cards:type_name -> card.v1.Card
	0,  // 5: card.v1.UpdateResponse.card:type_name -> card.v1.Card
	1,  // 6: card.v1.CardService.Add:input_type -> card.v1.AddRequest
	3,  // 7: card.v1.CardService.Get:input_type -> card.v1.GetRequest
	5,  // 8: card.v1.CardService.List:input_type -> card.v1.ListRequest
	7,  // 9: card.v1.CardService.Update:input_type -> card.v1.UpdateRequest
	9,  // 10: card.v1.CardService.Delete:input_type -> card.v1.DeleteRequest
	2,  // 11: card.v1.CardService.Add:output_type -> card.v1.AddResponse
	4,  // 12: card.v1.CardService.Get:output_type -> card.v1.GetResponse
	6,  // 13: card.v1.CardService.List:output_type -> card.v1.ListResponse
	8,  // 14: card.v1.CardService.Update:output_type -> card.v1.UpdateResponse
	10, // 15: card.v1.CardService.Delete:output_type -> card.v1.DeleteResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_user_v1_card_proto_init() }
func file_user_v1_card_proto_init() {
	if File_user_v1_card_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_card_proto_rawDesc), len(file_user_v1_card_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_v1_card_proto_goTypes,
		DependencyIndexes: file_user_v1_card_proto_depIdxs,
		MessageInfos:      file_user_v1_card_proto_msgTypes,
	}.Build()
	File_user_v1_card_proto = out.File
	file_user_v1_card_proto_goTypes = nil
	file_user_v1_card_proto_depIdxs = nil
}
