// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: file/v1/file.proto

package filev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// File is the client-side encrypted metadata of a stored file. The encrypted
// chunk bodies are not part of this message; they are streamed separately.
type File struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Meta        []byte                 `protobuf:"bytes,2,opt,name=meta"`
	xxx_hidden_ChunkCount  int32                  `protobuf:"varint,3,opt,name=chunk_count,json=chunkCount"`
	xxx_hidden_Version     int64                  `protobuf:"varint,4,opt,name=version"`
	xxx_hidden_CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt"`
	xxx_hidden_UpdatedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_file_v1_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *File) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *File) GetMeta() []byte {
	if x != nil {
		return x.xxx_hidden_Meta
	}
	return nil
}

func (x *File) GetChunkCount() int32 {
	if x != nil {
		return x.xxx_hidden_ChunkCount
	}
	return 0
}

func (x *File) GetVersion() int64 {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return 0
}

func (x *File) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *File) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_UpdatedAt
	}
	return nil
}

func (x *File) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *File) SetMeta(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Meta = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *File) SetChunkCount(v int32) {
	x.xxx_hidden_ChunkCount = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *File) SetVersion(v int64) {
	x.xxx_hidden_Version = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *File) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *File) SetUpdatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_UpdatedAt = v
}

func (x *File) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *File) HasMeta() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *File) HasChunkCount() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *File) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *File) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *File) HasUpdatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UpdatedAt != nil
}

func (x *File) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *File) ClearMeta() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Meta = nil
}

func (x *File) ClearChunkCount() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ChunkCount = 0
}

func (x *File) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Version = 0
}

func (x *File) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

func (x *File) ClearUpdatedAt() {
	x.xxx_hidden_UpdatedAt = nil
}

type File_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id         *string
	Meta       []byte
	ChunkCount *int32
	Version    *int64
	CreatedAt  *timestamppb.Timestamp
	UpdatedAt  *timestamppb.Timestamp
}

func (b0 File_builder) Build() *File {
	m0 := &File{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_Id = b.Id
	}
	if b.Meta != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_Meta = b.Meta
	}
	if b.ChunkCount != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_ChunkCount = *b.ChunkCount
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_Version = *b.Version
	}
	x.xxx_hidden_CreatedAt = b.CreatedAt
	x.xxx_hidden_UpdatedAt = b.UpdatedAt
	return m0
}

// FileHeader is the first message of an upload stream: encrypted metadata and
// the total number of chunks that follow.
type FileHeader struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Meta        []byte                 `protobuf:"bytes,1,opt,name=meta"`
	xxx_hidden_ChunkCount  int32                  `protobuf:"varint,2,opt,name=chunk_count,json=chunkCount"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *FileHeader) Reset() {
	*x = FileHeader{}
	mi := &file_file_v1_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileHeader) ProtoMessage() {}

func (x *FileHeader) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FileHeader) GetMeta() []byte {
	if x != nil {
		return x.xxx_hidden_Meta
	}
	return nil
}

func (x *FileHeader) GetChunkCount() int32 {
	if x != nil {
		return x.xxx_hidden_ChunkCount
	}
	return 0
}

func (x *FileHeader) SetMeta(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Meta = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *FileHeader) SetChunkCount(v int32) {
	x.xxx_hidden_ChunkCount = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *FileHeader) HasMeta() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *FileHeader) HasChunkCount() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *FileHeader) ClearMeta() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Meta = nil
}

func (x *FileHeader) ClearChunkCount() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ChunkCount = 0
}

type FileHeader_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Meta       []byte
	ChunkCount *int32
}

func (b0 FileHeader_builder) Build() *FileHeader {
	m0 := &FileHeader{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Meta != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Meta = b.Meta
	}
	if b.ChunkCount != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_ChunkCount = *b.ChunkCount
	}
	return m0
}

// FileChunk is one ordered, client-encrypted piece of a file body.
type FileChunk struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Idx         int32                  `protobuf:"varint,1,opt,name=idx"`
	xxx_hidden_Data        []byte                 `protobuf:"bytes,2,opt,name=data"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_file_v1_file_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_file_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FileChunk) GetIdx() int32 {
	if x != nil {
		return x.xxx_hidden_Idx
	}
	return 0
}

func (x *FileChunk) GetData() []byte {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *FileChunk) SetIdx(v int32) {
	x.xxx_hidden_Idx = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *FileChunk) SetData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *FileChunk) HasIdx() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *FileChunk) HasData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *FileChunk) ClearIdx() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Idx = 0
}

func (x *FileChunk) ClearData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Data = nil
}

type FileChunk_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Idx  *int32
	Data []byte
}

func (b0 FileChunk_builder) Build() *FileChunk {
	m0 := &FileChunk{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Idx != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Idx = *b.Idx
	}
	if b.Data != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Data = b.Data
	}
	return m0
}

// UploadRequest is a single frame of an upload stream: the header comes first,
// then one chunk per frame.
type UploadRequest struct {
	state              protoimpl.MessageState  `protogen:"opaque.v1"`
	xxx_hidden_Payload isUploadRequest_Payload `protobuf_oneof:"payload"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_file_v1_file_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_file_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UploadRequest) GetHeader() *FileHeader {
	if x != nil {
		if x, ok := x.xxx_hidden_Payload.(*uploadRequest_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *UploadRequest) GetChunk() *FileChunk {
	if x != nil {
		if x, ok := x.xxx_hidden_Payload.(*uploadRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

func (x *UploadRequest) SetHeader(v *FileHeader) {
	if v == nil {
		x.xxx_hidden_Payload = nil
		return
	}
	x.xxx_hidden_Payload = &uploadRequest_Header{v}
}

func (x *UploadRequest) SetChunk(v *FileChunk) {
	if v == nil {
		x.xxx_hidden_Payload = nil
		return
	}
	x.xxx_hidden_Payload = &uploadRequest_Chunk{v}
}

func (x *UploadRequest) HasPayload() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Payload != nil
}

func (x *UploadRequest) HasHeader() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Payload.(*uploadRequest_Header)
	return ok
}

func (x *UploadRequest) HasChunk() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Payload.(*uploadRequest_Chunk)
	return ok
}

func (x *UploadRequest) ClearPayload() {
	x.xxx_hidden_Payload = nil
}

func (x *UploadRequest) ClearHeader() {
	if _, ok := x.xxx_hidden_Payload.(*uploadRequest_Header); ok {
		x.xxx_hidden_Payload = nil
	}
}

func (x *UploadRequest) ClearChunk() {
	if _, ok := x.xxx_hidden_Payload.(*uploadRequest_Chunk); ok {
		x.xxx_hidden_Payload = nil
	}
}

const UploadRequest_Payload_not_set_case case_UploadRequest_Payload = 0
const UploadRequest_Header_case case_UploadRequest_Payload = 1
const UploadRequest_Chunk_case case_UploadRequest_Payload = 2

func (x *UploadRequest) WhichPayload() case_UploadRequest_Payload {
	if x == nil {
		return UploadRequest_Payload_not_set_case
	}
	switch x.xxx_hidden_Payload.(type) {
	case *uploadRequest_Header:
		return UploadRequest_Header_case
	case *uploadRequest_Chunk:
		return UploadRequest_Chunk_case
	default:
		return UploadRequest_Payload_not_set_case
	}
}

type UploadRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Payload:
	Header *FileHeader
	Chunk  *FileChunk
	// -- end of xxx_hidden_Payload
}

func (b0 UploadRequest_builder) Build() *UploadRequest {
	m0 := &UploadRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Header != nil {
		x.xxx_hidden_Payload = &uploadRequest_Header{b.Header}
	}
	if b.Chunk != nil {
		x.xxx_hidden_Payload = &uploadRequest_Chunk{b.Chunk}
	}
	return m0
}

type case_UploadRequest_Payload protoreflect.FieldNumber

func (x case_UploadRequest_Payload) String() string {
	md := file_file_v1_file_proto_msgTypes[3].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isUploadRequest_Payload interface {
	isUploadRequest_Payload()
}

type uploadRequest_Header struct {
	Header *FileHeader `protobuf:"bytes,1,opt,name=header,oneof"`
}

type uploadRequest_Chunk struct {
	Chunk *FileChunk `protobuf:"bytes,2,opt,name=chunk,oneof"`
}

func (*uploadRequest_Header) isUploadRequest_Payload() {}

func (*uploadRequest_Chunk) isUploadRequest_Payload() {}

type UploadResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_file_v1_file_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_file_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UploadResponse) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *UploadResponse) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *UploadResponse) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *UploadResponse) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

type UploadResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id *string
}

func (b0 UploadResponse_builder) Build() *UploadResponse {
	m0 := &UploadResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Id = b.Id
	}
	return m0
}

type DownloadRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DownloadRequest) Reset() {
	*x = DownloadRequest{}
	mi := &file_file_v1_file_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRequest) ProtoMessage() {}

func (x *DownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_file_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DownloadRequest) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *DownloadRequest) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *DownloadRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DownloadRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

type DownloadRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id *string
}

func (b0 DownloadRequest_builder) Build() *DownloadRequest {
	m0 := &DownloadRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Id = b.Id
	}
	return m0
}

// DownloadResponse is a single frame of a download stream: the encrypted
// metadata comes first, then the chunks in order.
type DownloadResponse struct {
	state              protoimpl.MessageState     `protogen:"opaque.v1"`
	xxx_hidden_Payload isDownloadResponse_Payload `protobuf_oneof:"payload"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DownloadResponse) Reset() {
	*x = DownloadResponse{}
	mi := &file_file_v1_file_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadResponse) ProtoMessage() {}

func (x *DownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_file_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DownloadResponse) GetMeta() []byte {
	if x != nil {
		if x, ok := x.xxx_hidden_Payload.(*downloadResponse_Meta); ok {
			return x.Meta
		}
	}
	return nil
}

func (x *DownloadResponse) GetChunk() *FileChunk {
	if x != nil {
		if x, ok := x.xxx_hidden_Payload.(*downloadResponse_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

func (x *DownloadResponse) SetMeta(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Payload = &downloadResponse_Meta{v}
}

func (x *DownloadResponse) SetChunk(v *FileChunk) {
	if v == nil {
		x.xxx_hidden_Payload = nil
		return
	}
	x.xxx_hidden_Payload = &downloadResponse_Chunk{v}
}

func (x *DownloadResponse) HasPayload() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Payload != nil
}

func (x *DownloadResponse) HasMeta() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Payload.(*downloadResponse_Meta)
	return ok
}

func (x *DownloadResponse) HasChunk() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Payload.(*downloadResponse_Chunk)
	return ok
}

func (x *DownloadResponse) ClearPayload() {
	x.xxx_hidden_Payload = nil
}

func (x *DownloadResponse) ClearMeta() {
	if _, ok := x.xxx_hidden_Payload.(*downloadResponse_Meta); ok {
		x.xxx_hidden_Payload = nil
	}
}

func (x *DownloadResponse) ClearChunk() {
	if _, ok := x.xxx_hidden_Payload.(*downloadResponse_Chunk); ok {
		x.xxx_hidden_Payload = nil
	}
}

const DownloadResponse_Payload_not_set_case case_DownloadResponse_Payload = 0
const DownloadResponse_Meta_case case_DownloadResponse_Payload = 1
const DownloadResponse_Chunk_case case_DownloadResponse_Payload = 2

func (x *DownloadResponse) WhichPayload() case_DownloadResponse_Payload {
	if x == nil {
		return DownloadResponse_Payload_not_set_case
	}
	switch x.xxx_hidden_Payload.(type) {
	case *downloadResponse_Meta:
		return DownloadResponse_Meta_case
	case *downloadResponse_Chunk:
		return DownloadResponse_Chunk_case
	default:
		return DownloadResponse_Payload_not_set_case
	}
}

type DownloadResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Payload:
	Meta  []byte
	Chunk *FileChunk
	// -- end of xxx_hidden_Payload
}

func (b0 DownloadResponse_builder) Build() *DownloadResponse {
	m0 := &DownloadResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Meta != nil {
		x.xxx_hidden_Payload = &downloadResponse_Meta{b.Meta}
	}
	if b.Chunk != nil {
		x.xxx_hidden_Payload = &downloadResponse_Chunk{b.Chunk}
	}
	return m0
}

type case_DownloadResponse_Payload protoreflect.FieldNumber

func (x case_DownloadResponse_Payload) String() string {
	md := file_file_v1_file_proto_msgTypes[6].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isDownloadResponse_Payload interface {
	isDownloadResponse_Payload()
}

type downloadResponse_Meta struct {
	Meta []byte `protobuf:"bytes,1,opt,name=meta,oneof"`
}

type downloadResponse_Chunk struct {
	Chunk *FileChunk `protobuf:"bytes,2,opt,name=chunk,oneof"`
}

func (*downloadResponse_Meta) isDownloadResponse_Payload() {}

func (*downloadResponse_Chunk) isDownloadResponse_Payload() {}

// ListRequest pages a user's files in chunks.
type ListRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_LastId      *string                `protobuf:"bytes,1,opt,name=last_id,json=lastId"`
	xxx_hidden_Limit       int32                  `protobuf:"varint,2,opt,name=limit"`
	xxx_hidden_Offset      int32                  `protobuf:"varint,3,opt,name=offset"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_file_v1_file_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_file_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListRequest) GetLastId() string {
	if x != nil {
		if x.xxx_hidden_LastId != nil {
			return *x.xxx_hidden_LastId
		}
		return ""
	}
	return ""
}

func (x *ListRequest) GetLimit() int32 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *ListRequest) GetOffset() int32 {
	if x != nil {
		return x.xxx_hidden_Offset
	}
	return 0
}

func (x *ListRequest) SetLastId(v string) {
	x.xxx_hidden_LastId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *ListRequest) SetLimit(v int32) {
	x.xxx_hidden_Limit = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *ListRequest) SetOffset(v int32) {
	x.xxx_hidden_Offset = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *ListRequest) HasLastId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ListRequest) HasLimit() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ListRequest) HasOffset() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ListRequest) ClearLastId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_LastId = nil
}

func (x *ListRequest) ClearLimit() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Limit = 0
}

func (x *ListRequest) ClearOffset() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Offset = 0
}

type ListRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	LastId *string
	Limit  *int32
	Offset *int32
}

func (b0 ListRequest_builder) Build() *ListRequest {
	m0 := &ListRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.LastId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_LastId = b.LastId
	}
	if b.Limit != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Limit = *b.Limit
	}
	if b.Offset != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Offset = *b.Offset
	}
	return m0
}

type ListResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Files *[]*File               `protobuf:"bytes,1,rep,name=files"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_file_v1_file_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_file_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListResponse) GetFiles() []*File {
	if x != nil {
		if x.xxx_hidden_Files != nil {
			return *x.xxx_hidden_Files
		}
	}
	return nil
}

func (x *ListResponse) SetFiles(v []*File) {
	x.xxx_hidden_Files = &v
}

type ListResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Files []*File
}

func (b0 ListResponse_builder) Build() *ListResponse {
	m0 := &ListResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Files = &b.Files
	return m0
}

type DeleteRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_file_v1_file_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_file_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteRequest) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *DeleteRequest) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *DeleteRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DeleteRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

type DeleteRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id *string
}

func (b0 DeleteRequest_builder) Build() *DeleteRequest {
	m0 := &DeleteRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Id = b.Id
	}
	return m0
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_file_v1_file_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_file_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type DeleteResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 DeleteResponse_builder) Build() *DeleteResponse {
	m0 := &DeleteResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

// UpdateMetaRequest changes only the encrypted metadata of a file; the chunk
// bodies are left untouched.
type UpdateMetaRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Meta        []byte                 `protobuf:"bytes,2,opt,name=meta"`
	xxx_hidden_Version     int64                  `protobuf:"varint,3,opt,name=version"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UpdateMetaRequest) Reset() {
	*x = UpdateMetaRequest{}
	mi := &file_file_v1_file_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetaRequest) ProtoMessage() {}

func (x *UpdateMetaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_file_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateMetaRequest) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *UpdateMetaRequest) GetMeta() []byte {
	if x != nil {
		return x.xxx_hidden_Meta
	}
	return nil
}

func (x *UpdateMetaRequest) GetVersion() int64 {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return 0
}

func (x *UpdateMetaRequest) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *UpdateMetaRequest) SetMeta(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Meta = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *UpdateMetaRequest) SetVersion(v int64) {
	x.xxx_hidden_Version = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *UpdateMetaRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *UpdateMetaRequest) HasMeta() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *UpdateMetaRequest) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *UpdateMetaRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *UpdateMetaRequest) ClearMeta() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Meta = nil
}

func (x *UpdateMetaRequest) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Version = 0
}

type UpdateMetaRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id      *string
	Meta    []byte
	Version *int64
}

func (b0 UpdateMetaRequest_builder) Build() *UpdateMetaRequest {
	m0 := &UpdateMetaRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Id = b.Id
	}
	if b.Meta != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Meta = b.Meta
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Version = *b.Version
	}
	return m0
}

type UpdateMetaResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_File *File                  `protobuf:"bytes,1,opt,name=file"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateMetaResponse) Reset() {
	*x = UpdateMetaResponse{}
	mi := &file_file_v1_file_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetaResponse) ProtoMessage() {}

func (x *UpdateMetaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_file_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateMetaResponse) GetFile() *File {
	if x != nil {
		return x.xxx_hidden_File
	}
	return nil
}

func (x *UpdateMetaResponse) SetFile(v *File) {
	x.xxx_hidden_File = v
}

func (x *UpdateMetaResponse) HasFile() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_File != nil
}

func (x *UpdateMetaResponse) ClearFile() {
	x.xxx_hidden_File = nil
}

type UpdateMetaResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	File *File
}

func (b0 UpdateMetaResponse_builder) Build() *UpdateMetaResponse {
	m0 := &UpdateMetaResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_File = b.File
	return m0
}

var File_file_v1_file_proto protoreflect.FileDescriptor

const file_file_v1_file_proto_rawDesc = "" +
	"\n" +
	"\x12file/v1/file.proto\x12\afile.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdb\x01\n" +
	"\x04File\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04meta\x18\x02 \x01(\fR\x04meta\x12\x1f\n" +
	"\vchunk_count\x18\x03 \x01(\x05R\n" +
	"chunkCount\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"A\n" +
	"\n" +
	"FileHeader\x12\x12\n" +
	"\x04meta\x18\x01 \x01(\fR\x04meta\x12\x1f\n" +
	"\vchunk_count\x18\x02 \x01(\x05R\n" +
	"chunkCount\"1\n" +
	"\tFileChunk\x12\x10\n" +
	"\x03idx\x18\x01 \x01(\x05R\x03idx\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"u\n" +
	"\rUploadRequest\x12-\n" +
	"\x06header\x18\x01 \x01(\v2\x13.file.v1.FileHeaderH\x00R\x06header\x12*\n" +
	"\x05chunk\x18\x02 \x01(\v2\x12.file.v1.FileChunkH\x00R\x05chunkB\t\n" +
	"\apayload\" \n" +
	"\x0eUploadResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"!\n" +
	"\x0fDownloadRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"_\n" +
	"\x10DownloadResponse\x12\x14\n" +
	"\x04meta\x18\x01 \x01(\fH\x00R\x04meta\x12*\n" +
	"\x05chunk\x18\x02 \x01(\v2\x12.file.v1.FileChunkH\x00R\x05chunkB\t\n" +
	"\apayload\"T\n" +
	"\vListRequest\x12\x17\n" +
	"\alast_id\x18\x01 \x01(\tR\x06lastId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"3\n" +
	"\fListResponse\x12#\n" +
	"\x05files\x18\x01 \x03(\v2\r.file.v1.FileR\x05files\"\x1f\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x10\n" +
	"\x0eDeleteResponse\"Q\n" +
	"\x11UpdateMetaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04meta\x18\x02 \x01(\fR\x04meta\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\"7\n" +
	"\x12UpdateMetaResponse\x12!\n" +
	"\x04file\x18\x01 \x01(\v2\r.file.v1.FileR\x04file2\xc4\x02\n" +
	"\vFileService\x12;\n" +
	"\x06Upload\x12\x16.file.v1.UploadRequest\x1a\x17.file.v1.UploadResponse(\x01\x12A\n" +
	"\bDownload\x12\x18.file.v1.DownloadRequest\x1a\x19.file.v1.DownloadResponse0\x01\x123\n" +
	"\x04List\x12\x14.file.v1.ListRequest\x1a\x15.file.v1.ListResponse\x12E\n" +
	"\n" +
	"UpdateMeta\x12\x1a.file.v1.UpdateMetaRequest\x1a\x1b.file.v1.UpdateMetaResponse\x129\n" +
	"\x06Delete\x12\x16.file.v1.DeleteRequest\x1a\x17.file.v1.DeleteResponseB1Z/gophkeeper/internal/shared/proto/file/v1;filev1b\beditionsp\xe8\a"

var file_file_v1_file_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_file_v1_file_proto_goTypes = []any{
	(*File)(nil),                  // 0: file.v1.File
	(*FileHeader)(nil),            // 1: file.v1.FileHeader
	(*FileChunk)(nil),             // 2: file.v1.FileChunk
	(*UploadRequest)(nil),         // 3: file.v1.UploadRequest
	(*UploadResponse)(nil),        // 4: file.v1.UploadResponse
	(*DownloadRequest)(nil),       // 5: file.v1.DownloadRequest
	(*DownloadResponse)(nil),      // 6: file.v1.DownloadResponse
	(*ListRequest)(nil),           // 7: file.v1.ListRequest
	(*ListResponse)(nil),          // 8: file.v1.ListResponse
	(*DeleteRequest)(nil),         // 9: file.v1.DeleteRequest
	(*DeleteResponse)(nil),        // 10: file.v1.DeleteResponse
	(*UpdateMetaRequest)(nil),     // 11: file.v1.UpdateMetaRequest
	(*UpdateMetaResponse)(nil),    // 12: file.v1.UpdateMetaResponse
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
}
var file_file_v1_file_proto_depIdxs = []int32{
	13, // 0: file.v1.File.created_at:type_name -> google.protobuf.Timestamp
	13, // 1: file.v1.File.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 2: file.v1.UploadRequest.header:type_name -> file.v1.FileHeader
	2,  // 3: file.v1.UploadRequest.chunk:type_name -> file.v1.FileChunk
	2,  // 4: file.v1.DownloadResponse.chunk:type_name -> file.v1.FileChunk
	0,  // 5: file.v1.ListResponse.files:type_name -> file.v1.File
	0,  // 6: file.v1.UpdateMetaResponse.file:type_name -> file.v1.File
	3,  // 7: file.v1.FileService.Upload:input_type -> file.v1.UploadRequest
	5,  // 8: file.v1.FileService.Download:input_type -> file.v1.DownloadRequest
	7,  // 9: file.v1.FileService.List:input_type -> file.v1.ListRequest
	11, // 10: file.v1.FileService.UpdateMeta:input_type -> file.v1.UpdateMetaRequest
	9,  // 11: file.v1.FileService.Delete:input_type -> file.v1.DeleteRequest
	4,  // 12: file.v1.FileService.Upload:output_type -> file.v1.UploadResponse
	6,  // 13: file.v1.FileService.Download:output_type -> file.v1.DownloadResponse
	8,  // 14: file.v1.FileService.List:output_type -> file.v1.ListResponse
	12, // 15: file.v1.FileService.UpdateMeta:output_type -> file.v1.UpdateMetaResponse
	10, // 16: file.v1.FileService.Delete:output_type -> file.v1.DeleteResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_file_v1_file_proto_init() }
func file_file_v1_file_proto_init() {
	if File_file_v1_file_proto != nil {
		return
	}
	file_file_v1_file_proto_msgTypes[3].OneofWrappers = []any{
		(*uploadRequest_Header)(nil),
		(*uploadRequest_Chunk)(nil),
	}
	file_file_v1_file_proto_msgTypes[6].OneofWrappers = []any{
		(*downloadResponse_Meta)(nil),
		(*downloadResponse_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_file_v1_file_proto_rawDesc), len(file_file_v1_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_file_v1_file_proto_goTypes,
		DependencyIndexes: file_file_v1_file_proto_depIdxs,
		MessageInfos:      file_file_v1_file_proto_msgTypes,
	}.Build()
	File_file_v1_file_proto = out.File
	file_file_v1_file_proto_goTypes = nil
	file_file_v1_file_proto_depIdxs = nil
}
